version: '2.1'

services:

    #service 1: Rabbitmq image creation
    rabbitmq:
      image: rmqimage
      container_name: rabbitmq
      hostname: rabbithost
      build :
        context : ./rabbitmq
        dockerfile: Dockerfile
      ports:
        - '15672:15672'
        - '5672:5672'
      restart: always
      healthcheck:
          test: ["CMD", "rabbitmq-diagnostics" ,"-q", "ping"]
          interval: 30s
          timeout: 30s
          retries: 10
    #service 2: mysql database image creation
    accountservice:
      image: accountservice-image
      container_name: accountservice
      hostname: accountservice-host
      build :
        context : ./AccountService
        dockerfile: Dockerfile
      ports:
        - '8080:8080'
      environment:
        transaction-service_get-transactions-url : transactionservice:8050/api/transactions/getTransactionsByAccountNumber
        transaction-service_get-balance-url : transactionservice:8050/api/transactions/getBalanceByAccountNumber
        transaction-service_new-transaction-queue : transaction
        spring_rabbitmq_addresses : amqp://account_service:1234@rabbitmq/banking 
      restart: always
      depends_on:
          rabbitmq :
            condition: service_healthy
    transactionservice:
      image: transactionservice-image
      container_name: transactionservice
      hostname: transactionservice-host
      build :
        context : ./TransactionService
        dockerfile: Dockerfile
      ports:
        - '8050:8050'
      environment:
        transaction-service_new-transaction-queue : transaction
        spring_rabbitmq_addresses : amqp://transaction_service:1234@rabbitmq/banking
      restart: always
      depends_on:
          rabbitmq :
            condition: service_healthy